get:
  summary: Get a product by produt ID
  operationId: getProduct
  tags:
    - Products
  parameters:
    - name: productId
      in: path
      required: true
      schema:
        type: integer
        format: int64
  responses:
    200:
      description: responses the product
      content:
        application/json:
          schema:
            $ref: '../openapi.yaml#/components/schemas/Product'
    404:
      description: a product does not found
put:
  summary: Update a product by product ID
  operationId: updateProducts
  tags:
    - Products
  parameters:
    - name: productId
      in: path
      required: true
      schema:
        type: integer
        format: int64
  responses:
    200:
      description: updated the product
      content:
        application/json:
          schema:
            $ref: '../openapi.yaml#/components/schemas/Product'
    404:
      description: a product does not found
delete:
  summary: Delete a product by product ID
  operationId: deleteProduct
  tags:
    - Products
  parameters:
    - name: productId
      in: path
      required: true
      schema:
        type: integer
        format: int64
  responses:
    204:
      description: request has been succeeded
    404:
      description: a product does not found
