openapi: 3.0.3

info:
  title: Workshop API
  version: 0.0.1
  contact:
    name: Sho SOBUE

servers:
  - url: http://localhost:8080/api/v1
    description: Local development

tags:
  - name: Products
    description: Product Management APIs
  - name: Orders
    description: Order Management APIs

paths:
  /products:
    $ref: './paths/products.yaml'
  /products/{productId}:
    $ref: './paths/products_productId.yaml'
  /orders:
    $ref: './paths/orders.yaml'
  /orders/{orderId}:
    $ref: './paths/orders_orderId.yaml'
  /orders/{orderId}/total:
    $ref: './paths/orders_orderId_total.yaml'
  /orders/{orderId}/items:
    $ref: './paths/orders_orderId_items.yaml'
  /orders/{orderId}/items/{itemId}:
    $ref: './paths/orders_orderId_items_itemId.yaml'
