openapi: 3.0.3

components:
  schemas:
    Product:
      properties:
        id:
          description: Product ID
          readOnly: true
          type: integer
          format: int64
        name:
          description: Product name
          required: true
          type: string
          minLength: 1
          maxLength: 1000
        currency:
          description: Currency of price
          required: true
          type: string
          enum:
            - USD
            - JPY
            - EUR
        price:
          description: Product price
          required: true
          type: number
          format: double
          minimum: 0.0
        stock:
          description: Stock quantity
          required: true
          type: integer
          format: int32
